name 'server_basic'
maintainer 'Tomas Norre Mikkelsen'
maintainer_email 'tomasnorre@gmail.com'
license 'Beer License'
description 'Installs/Configures server_basic'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
source_url 'https://github.com/tomasnorre/chef-server_bacis'
issues_url 'https://github.com/tomasnorre/chef-server_bacis/issues'
chef_version '~> 12'
supports 'ubuntu'
version '0.3.1'
